CREATE TABLE "COMPANY"
(
  "COMPANYID" NUMBER(30,0) NOT NULL ENABLE,
  "ACCOUNTID" NUMBER(30,0),
  "WEBID"     VARCHAR2(300 BYTE),
  "KEY_"      CLOB,
  "MX"        VARCHAR2(300 BYTE),
  "HOMEURL"   VARCHAR2(4000 BYTE),
  "LOGOID"    NUMBER(30,0),
  "SYSTEM"    NUMBER(1,0),
  "MAXUSERS"  NUMBER(30,0),
  PRIMARY KEY ("COMPANYID")
)