CREATE TABLE "LAYOUTSET"
(
  "LAYOUTSETID"          NUMBER(30,0) NOT NULL ENABLE,
  "GROUPID"              NUMBER(30,0),
  "COMPANYID"            NUMBER(30,0),
  "PRIVATELAYOUT"        NUMBER(1,0),
  "LOGO"                 NUMBER(1,0),
  "LOGOID"               NUMBER(30,0),
  "THEMEID"              VARCHAR2(300 BYTE),
  "COLORSCHEMEID"        VARCHAR2(300 BYTE),
  "WAPTHEMEID"           VARCHAR2(300 BYTE),
  "WAPCOLORSCHEMEID"     VARCHAR2(300 BYTE),
  "CSS"                  VARCHAR2(4000 BYTE),
  "PAGECOUNT"            NUMBER(30,0),
  "SETTINGS_"            VARCHAR2(4000 BYTE),
  "LAYOUTSETPROTOTYPEID" NUMBER(30,0),
  PRIMARY KEY ("LAYOUTSETID")
)