CREATE TABLE "VIRTUALHOST"
(
  "VIRTUALHOSTID" NUMBER(30,0) NOT NULL ENABLE,
  "COMPANYID"     NUMBER(30,0),
  "LAYOUTSETID"   NUMBER(30,0),
  "HOSTNAME"      VARCHAR2(300 BYTE),
  PRIMARY KEY ("VIRTUALHOSTID")
)